"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var categories_service_1 = require("./services/categories.service");
exports.CategoriesService = categories_service_1.CategoriesService;
var customer_roles_service_1 = require("./services/customer-roles.service");
exports.CustomerRolesService = customer_roles_service_1.CustomerRolesService;
var customers_service_1 = require("./services/customers.service");
exports.CustomersService = customers_service_1.CustomersService;
var languages_service_1 = require("./services/languages.service");
exports.LanguagesService = languages_service_1.LanguagesService;
//export { ManageClientsAdminService } from './services/manage-clients-admin.service';
var order_items_service_1 = require("./services/order-items.service");
exports.OrderItemsService = order_items_service_1.OrderItemsService;
var orders_service_1 = require("./services/orders.service");
exports.OrdersService = orders_service_1.OrdersService;
var product_attributes_service_1 = require("./services/product-attributes.service");
exports.ProductAttributesService = product_attributes_service_1.ProductAttributesService;
var product_category_mappings_service_1 = require("./services/product-category-mappings.service");
exports.ProductCategoryMappingsService = product_category_mappings_service_1.ProductCategoryMappingsService;
var products_service_1 = require("./services/products.service");
exports.ProductsService = products_service_1.ProductsService;
var shopping_cart_items_service_1 = require("./services/shopping-cart-items.service");
exports.ShoppingCartItemsService = shopping_cart_items_service_1.ShoppingCartItemsService;
var store_service_1 = require("./services/store.service");
exports.StoreService = store_service_1.StoreService;
// export { WebHookFiltersService } from './services/web-hook-filters.service';
// export { WebHookRegistrationsService } from './services/web-hook-registrations.service';
//# sourceMappingURL=services.js.map